### ISSUE TITLE
feedback: oops the user is empty

### ISSUE THREAD

**Issue by hisham2007** [cullaboration/userhook-sdk-android#2]
Many thanks for great effort.
sometimes when I use: 

`  UserHook.showFeedback();`

This message is displayed instead of feedback chat window:
`oops the user is empty`

**Comment by whynotmatt** [comment]
This should be fixed in the https://github.com/cullaboration/userhook-sdk-android/commit/1ea5386ba07d347fb880d001de20dc285406c3e6 commit.
