### ISSUE TITLE
feedback small improvement

### ISSUE THREAD

**Issue by hishambakr** [cullaboration/userhook-sdk-android#4]
when there is a new message and user clicks on:

`  UserHook.showFeedbackPrompt("You have a new response to your recently submitted feedback. Do you want to read it now?", "Read Now", "Later");
`

feedback screen should scroll down to latest message when screen opens

**Comment by hisham2007** [comment]
also when a reply come from developer, a notification appears but when click on it, it doesn't open feedback screen

**Comment by hisham2007** [comment]
by the way , i opened these issues multiple days ago and you should reply quicker than that. you are userhook. come on :)

**Comment by whynotmatt** [comment]
We've made some commits to fix these issues in https://github.com/cullaboration/userhook-sdk-android/commit/3c0bcfdcb8d6806e0aafee2dc84034b43a3dd3f8
